resolver: lts-14.27
packages:
- 'hs'
- '.'
extra-deps:
- usb-1.3.0.6
- bindings-libusb-1.4.5.0
- git: git://github.com/lpsmith/linux-inotify
  commit: b441753a199e0034a42b1f6b9fc8499c673063cb
flags:
  blink1:
    usb: false
